### ISSUE TITLE
cannot load such file -- ./lib/signal_tools/technicals/common (LoadError)

### ISSUE THREAD

**Issue by hostingnuggets** [whitethunder/signal_tools#3]
Hi,

I just installed your gem with Ruby 3.0.2 but it does not seem to work as a `require 'signal_tools'` spits out the following error:

```
<internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ./lib/signal_tools/technicals/common (LoadError)
	from <internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/user/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/signal_tools-0.3.1/lib/signal_tools/stock.rb:1:in `<top (required)>'
	from <internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/user/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/signal_tools-0.3.1/lib/signal_tools.rb:2:in `<top (required)>'
	from <internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from s.rb:1:in `<main>'
<internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- signal_tools (LoadError)
	from <internal:/home/user/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from s.rb:1:in `<main>'
```

Is this gem maybe not compatible with Ruby 3?

**Comment by whitethunder** [comment]
@hostingnuggets Sorry, just saw this. I have not tested this on Ruby 3 at all so decent chance it's not compatible.

**Comment by hostingnuggets** [comment]
Thanks for your feedback. Any chances you will make your gem compatible with Ruby 3 in the near future?
